- wildcards/modifiers/strength/high.txt
- wildcards/modifiers/strength/low.txt
- wildcards/modifiers/strength/med.txt
- wildcards/modifiers/tags/aesthetic.txt
- wildcards/modifiers/tags/art-movement.txt
- wildcards/modifiers/tags/color.txt
- wildcards/modifiers/tags/light.txt
- wildcards/modifiers/tags/medium.txt
- wildcards/modifiers/tags/mood.txt
- wildcards/modifiers/tags/perspective.txt
- wildcards/modifiers/tags/photography.txt
- wildcards/modifiers/tags/pop-culture.txt
- wildcards/modifiers/tags/quality.txt
- wildcards/modifiers/tags/setting.txt
- wildcards/modifiers/tags/style.txt
[Notion database with examples for each modifier](https://proximacentaurib.notion.site/2b07d3195d5948c6a7e5836f9d535592)
> Add modifiers from parrot zone's modifier studies

- prompts/generators/magicprompt.py
- scripts/dynamic_prompting.py
Found a few small bugs I introduced in that other PR.  This should fix those up, including a better fix to #54.
> Minor fixes for Magic Prompt

- ui/wildcards_tab.py
I'd recommend also making it clear that it will delete all files in your wildcards folder.
> Fixing typo

- scripts/dynamic_prompting.py
- ui/wildcards_tab.py
Refs https://github.com/adieyal/dynamicprompts/pull/7
> Use wildcard_manager.path now that it's a thing

- .gitignore
- prompts/consts.py
- prompts/generator_builder.py
- pyproject.toml
- requirements.txt
- scripts/dynamic_prompting.py
- tests/prompts/test_generator_builder.py
This enables magic prompt blocklisting with dynamicprompts 0.4.0.
> Magic prompt blocklist

- ui/save_params.py
> Guard against no `p` in image_save_params

- javascript/dynamic_prompting.js
> Prevent Uncaught TypeError repeating onTick

- helptext.html
- sd_dynamic_prompts/dynamic_prompting.py
> Show dynamicprompts library version in help text

- docs/CHANGELOG.md
- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/helpers.py
- tests/prompts/test_helpers.py
Extracted get seeds to helpers.py
Ensured that seeds are always integers
Fixed subseed implementation
> Fixes #271

- docs/CHANGELOG.md
- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/ui/wildcards_tab.py
See - https://github.com/adieyal/sd-dynamic-prompts/pull/332#pullrequestreview-1357817222
> Minor code refactor

- sd_dynamic_prompts/attention_generator.py
- sd_dynamic_prompts/generator_builder.py
- tests/prompts/test_attention_generator.py
Fixes #327
Reimplementation of https://github.com/adieyal/dynamicprompts/pull/59
> Don't allow attention grabber to mess with A1111 special syntax

- docs/CHANGELOG.md
- sd_dynamic_prompts/dynamic_prompting.py
> Bug/Magic Prompt on Macs not working

- javascript/dynamic_prompting.js
- requirements.txt
- sd_dynamic_prompts/callbacks.py
- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/ui/wildcards_tab.py
- tests/prompts/test_generator_builder.py
PR for compatibility with the new wildcard backend in adieyal/dynamicprompts#56.
> New Wildcards compatibility

- docs/CHANGELOG.md
- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/frozenprompt_generator.py
- sd_dynamic_prompts/generator_builder.py
- sd_dynamic_prompts/helpers.py
- tests/prompts/test_frozenprompt_generator.py
- tests/prompts/test_generator_builder.py
> Freezing the prompt if variation strength is > 0

- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/helpers.py
- tests/prompts/test_helpers.py
Fix for Issue #190 - it seems to be working for me, but probably not the cleanest solution.
> Bugfix Issue #190 - Fixed seeds only within combinatorial batch

- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/settings.py
Added option to auto purge cache
Lazy way to do this
> Added option to auto purge cache

- sd_dynamic_prompts/dynamic_prompting.py
Noticed these bad boys while running with `PYTHONTRACEMALLOC=1`.
> Fix file handle resource leaks

- sd_dynamic_prompts/version_tools.py
> Honor --skip-install

- sd_dynamic_prompts/dynamic_prompting.py
This PR
* simplifies the HR prompt code from #495 a bit
* fixes #497 to make the addon more compatible with older and/or fork versions of the webui (by looking at whether the `all_hr_prompts` field is a thing at all).
@brimston3 Care to review that I got things right since #495 is your code?
> HR prompt improvements

- install.py
- sd_dynamic_prompts/version_tools.py
Fixes #499.
Hopefully now we have a robust install system...
> install: only invoke install for missing deps

- javascript/dynamic_prompting.js
- sd_dynamic_prompts/wildcards_tab.py
Inspired by #546, this simplifies the Wildcard Manager tab a bit and adds simple functionality to filter the tree by substring:
https://github.com/adieyal/sd-dynamic-prompts/assets/58669/525dfc9e-70c3-49f7-8c2a-9d0b97f9e862
cc @bee1850 (being the author of #546)
> Wildcard Manager Search

- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/helpers.py
- sd_dynamic_prompts/paths.py
- sd_dynamic_prompts/settings.py
- sd_dynamic_prompts/wildcards_tab.py
- tests/prompts/test_helpers.py
This 
* moves path-related bits and pieces to another module
* simplifies the magic prompt models file determination and reading 
Extracted from a future PR...
> Refactor paths and magic prompt models file read

- README.md
- docs/tutorial.md
Thanks for this cool extension.  Hope your Hacktoberfest is going well.  :shipit:
> Adding some details on wildcard setup

- sd_dynamic_prompts/callbacks.py
- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/pnginfo_saver.py
- tests/prompts/ui/test_pnginfo_saver.py
Related to #691 – will make it even simpler...
cc @w-e-w
> Simplify strip_template_info

- collections/artists/Photography/by_country/luxembourg
- collections/artists/Photography/by_country/luxembourg.txt
consistency, missing .txt extension
> Rename luxembourg to luxembourg.txt

- sd_dynamic_prompts/wildcards_tab.py
> Use gradio 3.34.0+ `scale` instead of `full_width`

- sd_dynamic_prompts/attention_generator.py
- sd_dynamic_prompts/generator_builder.py
- sd_dynamic_prompts/magic_prompt.py
- sd_dynamic_prompts/special_syntax.py
- tests/prompts/test_magic_prompts.py
> Make Magic Prompts aware of LoRA syntax too

- pyproject.toml
This should resolve https://github.com/adieyal/sd-dynamic-prompts/issues/743 via https://github.com/adieyal/dynamicprompts/pull/122 and also enables the [other new things in dp 0.31.0](https://github.com/adieyal/dynamicprompts/releases/tag/v0.31.0):
* Wrap command: https://github.com/adieyal/dynamicprompts/pull/102
* Support Preserving Variable Values: https://github.com/adieyal/dynamicprompts/pull/115
* Dynamic Wildcards: https://github.com/adieyal/dynamicprompts/pull/114
* Single-string collections: https://github.com/adieyal/dynamicprompts/pull/113
> Require dynamicprompts 0.31.0

- sd_dynamic_prompts/dynamic_prompting.py
> Register settings before Script.__init__()
