- README.md
- dynamic_prompting.py
This PR includes a new feature where the number of choices is random from a provided range.
It extends the quantity syntax (`3$$`) to optionally include a lower and upper bound (`1-3$$`).
The quantity of choices is randomly, uniformly selected from the interval including both bounds for each batch.
0 is a valid lower bound.
This PR also adds spaces between prompts (previously `{2$$a|b}` would return `a,b` instead of `a, b`). This has an impact on tokenization and may improve results (not tested).
Documentation is updated and obsolete inline documentation (for nesting) is removed.
Version is bumped to 0.3.
> Create range syntax: 1-3$$

- dynamic_prompting.py
- javascript/dynamic_prompting.js
Support folders in the `scripts/wildcards`
Added info
```
Note
Folder depth is only 1!! Folders add organization when having multiple wildcards.
Wildcards txt documents need to be in a folder, example:
 • Correct: scripts/wildcards/<folder>/*.txt
 • Incorrect: scripts/wildcards/*.txt
If the groups wont drop down click here to fix the issue.
Syntax
In order to use a wildcard the prefix must be a folder name: __<folder>.wildcard__, example: __sd.wildcard__
The folder name will be provided in the dropdowns. 
```
Added `javascript/dynamic_prompting.js` for the dropout
Wildcard are displayed in groups(folders), the dropout names are the folder names in `scripts/wildcards/`
current issue where sometimes the javascript function isn't called so that means the dropout wont work. the workaround is …
> Folders for organization 

- scripts/dynamic_prompting.py
Closes #25
I've wrapped the UI in an accordion to alleviate cluttering the rest of the UI (much like when the script wasn't selected in the dropdown previously). Example below:
Tested with no noticeable issues. Works with other scripts such as the X/Y plot.
> Initial conversion to `AlwaysVisible` script

- install.py
`run_pip` in `launch.py` already appends the `Installing` to the `desc` message.
```python
def run_pip(args, desc=None):
index_url_line = f' --index-url {index_url}' if index_url != '' else ''
return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
```
> run_pip appends Installing to install message

- .gitignore
- README.md
- helptext.html
- prompts/generators/randomprompt.py
- pyproject.toml
- tests/prompts/generators/test_combinationselector.py
- tests/prompts/generators/test_randomprompt.py
This PR introduces the ability to specify relative weights for all the variants in a dynamic prompt set.
This is purely additive, and should not modify the current behavior of existing prompts.
For example, say we wanted to generate photos of balls. We want to make it generate 3x as many photos of blue balls than red balls. We can do this by giving "blue" a weight of 3.0, and leaving "red" at the default weight of 1.0:
```
photo of a {3::blue|red} ball
```
Note that this is equivalent to doing the following in the current version:
```
photo of a {blue|blue|blue|red} ball
```
This new syntax is just a lot more succinct.
Here's another example: Generate photo portraits of men and women of different races, proportional to U.S. population demographics:
```
photo portrait of a …
```
> add support for weighted variants

- install.py
for some reason that check is case sensitive, so it was attempting a reinstall every single time you start the WebUI. Fixed with this easy case correction.
> fix install.py case sensitive is_installed check

- install.py
I don't see a reason to try and look for the given versions of the requirements; we could just tell `pip` to try and make sure those versions are available and that's that.
NB: I haven't tried this out yet, just throwing it out there. Let me know what you think, @adieyal!
Might help with #207.
> Simplify install script

- javascript/dynamic_prompting.js
I'm trying to see if I can update webui to use Gradio 3.22.1. I encountered an issue where this extension modifies the DOM and triggers webui's `onUiUpdate` MutationObserver in an infinite loop. This change should fix that issue (and be compatible with current Gradio also)
> Fix infinite recursion in Gradio 3.22.1

- docs/CHANGELOG.md
- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/ui/wildcards_tab.py
See https://github.com/adieyal/sd-dynamic-prompts/issues/270.
According to the [docs](https://docs.python.org/3/library/os.html#os.linesep), os.linesep should not be used when writing in text mode. Thanks to @Vonpiper for spotting this.
> Fixed bug causing unwanted newlines in wildcards

- sd_dynamic_prompts/dynamic_prompting.py
I'm not sure at all this is the right fix, as my eyes kinda glaze over trying to figure out what the difference between hr_prompt, hr_prompts, all_hr_prompts etc. in the webui is.
However, with this, hires fix doesn't _crash_. 
Refs https://github.com/adieyal/sd-dynamic-prompts/issues/474 (won't say it fixes it at this point).
The webui commit that caused this regression is https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ff0e17174f8d93a71fdd5a4a80a4629bbf97f822
> Make hires fix not crash with combinatorial processing

- install.py
Fixes #486 (though I don't understand why this is needed...).
> install.py: try to patch sys.path if the extension is not there?

- sd_dynamic_prompts/dynamic_prompting.py
The idea is if the hr params match the prompt params, overwrite. But otherwise force the hr prompt into a condition that won't blow up under combinatorial by expanding the first or only hr prompt into all slots as needed.
Where this goes wrong is if an extension further up stack from us fills in all_hr_prompts/all_hr_negative_prompts and we ignore the variations in other slots. Not sure the best way to address that at this time.
> slightly better hires fix.

- sd_dynamic_prompts/version_tools.py
...  to have a correct `pip install` command.
It used to say `pip install ~=0.123`, which was plain wrong and confusing.
> Fix the invalid install warning message

- sd_dynamic_prompts/helpers.py
Currently, cross-production of positive and negative prompts aren't performed well ~(well, technically, the cross-product for them is not performed at all)~.
<details>
<summary>First example</summary>
| Prompt | Negative prompt |
| ------ | --------------- |
| cat    | {blurry\|ugly}  |
These prompts are converted into:
| Prompt | Negative prompt |
| ------ | --------------- |
| cat    | blurry          |
e.g. only first negative prompt combination is used.
</details>
<details>
<summary>Second example</summary>
| Prompt          | Negative prompt |
| --------------- | --------------- |
| {1\|2\|3\|4\|5} | {7\|8}          |
These prompts are converted into:
| Prompt | Negative prompt |
| ------ | --------------- |
| 1      | 7               |
| 2      | 8               |
| 3      | 7 …
> combinatorial: cross product positive and negative prompt combinations

- sd_dynamic_prompts/callbacks.py
- sd_dynamic_prompts/dynamic_prompting.py
- sd_dynamic_prompts/pnginfo_saver.py
- tests/prompts/ui/test_pnginfo_saver.py
over at webui we recive a bug reort
[Bug]: Dynamic Prompt Metadata in blocks "Read Generation Parameters from Prompt" if extension is missing/disabled 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14201#issuecomment-1839119678
as far as I can tell this is caused by sd-dynamic-prompts using an unorthodox method of writing the pnginfo
when `opts.dp_write_raw_template` is enabled
wrining pnginfo in newline causing the webui pnginfo parser webui break as I believe you are aware, base on 
do you have implemented a call back to remove the extra pnginfo added by this extension
https://github.com/adieyal/sd-dynamic-prompts/blob/aedb3e4b91026351981f8412eb9e2e74167fdcff/sd_dynamic_prompts/pnginfo_saver.py#L45
in other words if one does not have dynamic-prompts, the pnginfo syntax …
> Use orthodox method for pnginfo

- sd_dynamic_prompts/dynamic_prompting.py
Small followup on #691.
cc @w-e-w
> Don't emit empty template/negative template into infotext

- docs/CHANGELOG.md
- docs/SYNTAX.md
- docs/resources.md
- docs/tutorial.md
This is in preparation to sync the documentation into the `dynamicprompts` tree too.
> Improve documentation slightly

- .github/workflows/test.yml
- tests/prompts/test_attention_generator.py
dynamicprompts v0.26.0+ (https://github.com/adieyal/dynamicprompts/pull/85) doesn't require spaCy for attention, so we can test it in CI here too.
> Run attention generator tests without spaCy

- sd_dynamic_prompts/magic_prompt.py
- tests/prompts/test_magic_prompts.py
> Hotfix for #708.

- javascript/dynamic_prompting.js
- sd_dynamic_prompts/wildcards_tab.py
Fixes https://github.com/adieyal/sd-dynamic-prompts/issues/736.
> Debounce wildcard search for large hierarchies

- sd_dynamic_prompts/magic_prompt.py
- tests/prompts/test_magic_prompts.py
> Deduplicate commas in generated magic prompts

- docs/SYNTAX.md
Correct / extend wildcard YAML weighted wildcard example. This version can be copied into a .yaml file directly and will function as-is.
> YAML weighted wildcard example tweak
